apiVersion: apps/v1
kind: Deployment
metadata:
  name: userMgmt
  labels:
    app: userMgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userMgmt
  template:
    metadata:
      labels:
        app: userMgmt
    spec:
      containers:
        - name: userMgmt
          image: username/userMgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5