apiVersion: apps/v1
kind: Deployment
metadata:
  name: carMgmt
  labels:
    app: carMgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carMgmt
  template:
    metadata:
      labels:
        app: carMgmt
    spec:
      containers:
        - name: carMgmt
          image: username/carMgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5