server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: carRental
          uri: http://localhost:8081
          predicates:
            - Path=/carRents/**, 
        - id: carMgmt
          uri: http://localhost:8082
          predicates:
            - Path=/carMgmts/**, 
        - id: view
          uri: http://localhost:8083
          predicates:
            - Path=, /totalCarLists/**
        - id: userMgmt
          uri: http://localhost:8084
          predicates:
            - Path=/memberMgmts/**, 
        - id: payment
          uri: http://localhost:8085
          predicates:
            - Path=/payments/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: carRental
          uri: http://carRental:8080
          predicates:
            - Path=/carRents/**, 
        - id: carMgmt
          uri: http://carMgmt:8080
          predicates:
            - Path=/carMgmts/**, 
        - id: view
          uri: http://view:8080
          predicates:
            - Path=, /totalCarLists/**
        - id: userMgmt
          uri: http://userMgmt:8080
          predicates:
            - Path=/memberMgmts/**, 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
